import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CONTENT_DIR = path.join(__dirname, '../content');
const OUTPUT_FILE = path.join(__dirname, '../src/data/profile.ts');

function getFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(file => file.endsWith('.md'));
}

function parseFile(filePath) {
  const fileContent = fs.readFileSync(filePath, 'utf8');
  const { data, content } = matter(fileContent);
  return { ...data, content: content.trim() };
}

function generateData() {
  console.log('Generating data from content files...');

  // 1. Parse Profile Info
  const profilePath = path.join(CONTENT_DIR, 'profile.json');
  let profileData = {
    name: 'Ajith Srikanth',
    title: 'Advanced Manufacturing Engineer',
    email: 'ajithsrikanth.f@northeastern.edu',
    socials: {}
  };

  if (fs.existsSync(profilePath)) {
    try {
      const profileJson = JSON.parse(fs.readFileSync(profilePath, 'utf8'));
      profileData = { ...profileData, ...profileJson };
    } catch (e) {
      console.error('Error parsing profile.json:', e);
    }
  }

  // 2. Parse Experience
  const experienceDir = path.join(CONTENT_DIR, 'experience');
  const experience = getFiles(experienceDir).map(file => {
    const data = parseFile(path.join(experienceDir, file));
    // Convert markdown bullets to array if needed, or keep as raw text
    // For now, let's assume the content is a list of bullets
    const bullets = data.content
      .split('\n')
      .map(line => line.replace(/^-\s*/, '').trim())
      .filter(line => line.length > 0);

    return {
      company: data.company || 'Unknown Company',
      role: data.role || 'Unknown Role',
      location: data.location,
      start: data.start,
      end: data.end,
      bullets
    };
  }).sort((a, b) => b.start.localeCompare(a.start)); // Sort by date descending

  // 3. Parse Projects
  const projectsDir = path.join(CONTENT_DIR, 'projects');
  const projects = getFiles(projectsDir).map(file => {
    const data = parseFile(path.join(projectsDir, file));
    return {
      id: data.id || file.replace('.md', ''),
      title: data.title || 'Untitled Project',
      subtitle: data.subtitle,
      category: data.category || 'Other',
      timeline: data.timeline || data.date,
      teamSize: data.teamSize,
      status: data.status,
      summary: data.summary || data.content.slice(0, 200) + '...', // Use summary frontmatter or truncate content
      content: data.content, // Keep full content available
      technologies: data.tech || data.technologies || [],
      impact: data.impact || [],
      links: data.links || {},
      businessContext: data.businessContext,
      challenge: data.challenge,
      scope: data.scope || [],
      technicalSolution: data.technicalSolution || {},
      quantifiedResults: data.quantifiedResults || {},
      images: data.images || [],
      recognition: data.recognition || [],
      researchContributions: data.researchContributions,
      educationalImpact: data.educationalImpact,
      aiEfficiency: data.aiEfficiency,
      uniqueAspects: data.uniqueAspects,
      date: data.date // For sorting
    };
  }).sort((a, b) => {
    // Sort by date descending
    if (!a.date) return 1;
    if (!b.date) return -1;
    return new Date(b.date) - new Date(a.date);
  });

  // 4. Parse Writings
  const writingsDir = path.join(CONTENT_DIR, 'writing');
  const writings = getFiles(writingsDir).map(file => {
    const data = parseFile(path.join(writingsDir, file));
    return {
      title: data.title,
      summary: data.content,
      url: data.url || '#',
      tags: data.tags || [],
      date: data.date
    };
  }).sort((a, b) => {
    if (!a.date) return 1;
    if (!b.date) return -1;
    return new Date(b.date) - new Date(a.date);
  });

  // 5. Parse Certifications
  const certifications = profileData.certifications || [];

  // Construct the final object
  const fullProfile = {
    ...profileData,
    experience,
    projects,
    writings,
    certifications
  };

  // Write to src/data/profile.ts
  const fileContent = `// Auto-generated by scripts/generate-data.mjs
export interface Experience {
  company: string;
  role: string;
  location?: string;
  start: string;
  end: string;
  bullets: string[];
}

export interface Project {
  id: string;
  title: string;
  subtitle?: string;
  category?: string;
  timeline?: string;
  teamSize?: string;
  status?: string;
  summary: string;
  content?: string;
  technologies: string[];
  impact?: string[];
  links?: {
    demo?: string;
    repo?: string;
    case_study?: string;
    papers?: string;
  };
  businessContext?: string;
  challenge?: string;
  scope?: string[];
  technicalSolution?: { [key: string]: string[] };
  quantifiedResults?: { [key: string]: string };
  images?: string[];
  recognition?: string[];
  researchContributions?: string[];
  educationalImpact?: string[];
  aiEfficiency?: string[];
  uniqueAspects?: string[];
}

export interface Writing {
  title: string;
  summary: string;
  url: string;
  tags?: string[];
  date?: string;
}

export interface Profile {
  name: string;
  title?: string;
  location?: string;
  email: string;
  socials?: { [key: string]: string };
  linkedin: string;
  github: string;
  skills: { [group: string]: string[] };
  experience: Experience[];
  projects: Project[];
  writings: Writing[];
  certifications: string[];
}

export const profile: Profile = ${JSON.stringify(fullProfile, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`Successfully generated ${OUTPUT_FILE} `);
}

generateData();
